### PR TITLE
Fix #407 by enhancing grammar

### LINKED ISSUE #407: Unknown DEFERRABLE Keyword
I am trying to parse the following string:

`ALTER TABLE TBL_S_TNE`
`ADD CONSTRAINT cst_pk_S_TNE`
`    PRIMARY KEY (S_I) DEFERRABLE NOVALIDATE;`

Am I obtain:
net.sf.jsqlparser.parser.ParseException: Encountered " <S_IDENTIFIER> "DEFERRABLE "" at line 3, column 23.
Was expecting one of:
    <EOF> 
    ";" ...
    "," ...

PS: you can ask me for a Pull Request if you are interested.

### PR DESCRIPTION
**Pull request by cmoine**

### CODE REVIEW

File: src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java [hunk 1]
```diff
@@ -76,47 +101,47 @@ public void testAlterTableDropColumn() throws JSQLParserException {
...
-		assertEquals(alterExpression.getConstraintName(), "YYY");
+        final String sql = "ALTER TABLE test DROP CONSTRAINT YYY";
+        Statement stmt = CCJSqlParserUtil.parse(sql);
+        assertStatementCanBeDeparsedAs(stmt, sql);
+        AlterExpression alterExpression = ((Alter) stmt).getAlterExpressions().get(0);
+        assertEquals(alterExpression.getConstraintName(), "YYY");
     }
 
     public void testAlterTablePK() throws JSQLParserException {
-		final String sql = "ALTER TABLE `Author` ADD CONSTRAINT `AuthorPK` PRIMARY KEY (`ID`)";
```
Comment (wumpz) [inline src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java]: Looks like you are correcting my formating issues ... 👍
