### PR TITLE
Closes #1583:: Implement Postgresql optional TABLE in TRUNCATE

### LINKED ISSUE #1583: Postgresql: TRUNCATE does not require TABLE
I see this in scripts: 

`TRUNCATE myfancytable;`

This is allowed by Postgresql:

https://www.postgresql.org/docs/current/sql-truncate.html

```
TRUNCATE [ TABLE ] [ ONLY ] name [ * ] [, ... ]
    [ RESTART IDENTITY | CONTINUE IDENTITY ] [ CASCADE | RESTRICT ]
```

However, the parser complains with: 

```
net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "myfancytable" <S_IDENTIFIER>
    at line 3, column 10.

Was expecting:

    "TABLE"
```

### PR DESCRIPTION
**Pull request by d2a-raudenaerde**
Implemented Postgresql optional TABLE in TRUNCATE.
Closes #1583

### CODE REVIEW

File: src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java [hunk 1]
```diff
@@ -41,6 +41,23 @@ public void testTruncate() throws Exception {
         assertEquals(statement, truncate.toString());
     }
 
+    @Test
+    public void testTruncatePostgresqlWithoutTableName() throws Exception {
```
Comment (wumpz) [inline src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java:45]: JSqlParser tries to rebuild the original SQL from its object tree. With your change, there would be always a `table` part. Use `assertSqlCanBeParsedAndDeparsed(statement)` to ensure the rebuilding behaviour. You have to introduce a flag, if the `table` keyword is used or not and then use this in the `toString` method of `Truncate` and the fitting deparser.

**Review by wumpz — CHANGES_REQUESTED** [review]

File: src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java (hunk 1 above)
Comment (d2a-raudenaerde) [reply src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java:52]: I see. I updated the PR with the flags (also for `ONLY`). 

btw.
I also noticed there is a bit of an overlap between the `StatementDeparser` `visit(Truncate t)` and the `toString()` of the `Truncate`.  I think you want to keep things loosely coupled, but added a `deparse()` method to the `Statement` interface might be a way to prevent this code duplicating, as the toString() could simply call `deparse()`. The reason I would be tempted do this, is that the project _forces_ you to have a deparse implementation for each statement.

**Review by wumpz — APPROVED** [review]
