### PR TITLE
Closes #965 added Oracle GRANT statement

### LINKED ISSUE #965: GRANT statement not supported
**Describe the bug**
GRANT statement not supported 

**To Reproduce**
1. GRANT SELECT ON Student TO P2
2. Parsing this SQL using JSqlParser with this statements
3. Encountered unexpected token: "GRANT" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

    "ALTER"
    "CALL"
    "COMMENT"
    "COMMIT"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "INSERT"
    "MERGE"
    "REPLACE"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUES"
    "WITH"
'

**Expected behavior**
Must be processed

**System**
 - Oracle
- 1.8
- JSqlParser 3.1

### PR DESCRIPTION
**Pull request by zhumaliev-rv**

### CODE REVIEW

File: src/test/java/net/sf/jsqlparser/statement/grant/GrantTest.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+        assertEquals(true, grant.getUsers().stream().anyMatch(s -> s.equals("u")));
+        assertEquals(true, grant.getUsers().stream().anyMatch(s -> s.equals("u2")));
+
+        assertEquals(statement, grant.toString());
+        assertEquals(null, grant.getRole());
+    }
+
+    @Test
+    public void testDropRestrictIssue510() throws JSQLParserException {
+        String statement = "GRANT role1 TO u, u2";
```
Comment (wumpz) [inline src/test/java/net/sf/jsqlparser/statement/grant/GrantTest.java:60]: This and the following test method names should be changed ...
