### PR TITLE
fixes #525

### LINKED ISSUE #525: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
```
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
String currentDate = dateFormat.format(new Date());
```

```
expressionList.getExpressions()
                        .add(new TimestampValue(currentDate ));
```

Exception:
```
Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql.Timestamp.valueOf(Timestamp.java:237)
	at net.sf.jsqlparser.expression.TimestampValue.<init>(TimestampValue.java:34)
```

### PR DESCRIPTION
**Pull request by yidasanqian**

### CODE REVIEW

File: src/test/java/net/sf/jsqlparser/expression/TimestampValueTest.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import java.util.Locale;
+
+/**
+ * @author Linyu Chen
+ */
+public class TimestampValueTest {
+
+    @Test
+    public void testTimestampValue() throws JSQLParserException {
+        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
```
Comment (wumpz) [inline src/test/java/net/sf/jsqlparser/expression/TimestampValueTest.java]: It would be better to test only TimestampValue without this sql changing stuff around. Its a unit test so keep it simple.

**Comment by yidasanqian** [comment]
No,do it please
